# Generated by Django 3.1.4 on 2021-01-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
        ('users', '0002_remove_profile_vatsim'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='simulators',
            field=models.ManyToManyField(null=True, to='mods.Mod'),
        ),
    ]
