# Generated by Django 3.1.4 on 2021-01-25 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('bio', models.TextField(blank=True, max_length=2000, null=True)),
                ('twitter', models.CharField(blank=True, help_text='Enter your Twitter username. NOT the link.', max_length=25)),
                ('vatsim', models.CharField(blank=True, max_length=25)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile')),
                ('header_image', models.ImageField(default='default.jpg', upload_to='profile/header/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
