# Generated by Django 3.1.6 on 2021-04-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0007_auto_20210412_1407'),
        ('users', '0003_profile_simulators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='simulators',
            field=models.ManyToManyField(to='mods.Mod'),
        ),
    ]
