# Generated by Django 3.1.6 on 2021-02-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_modsgallery_image_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='description',
            field=models.TextField(max_length=10000),
        ),
    ]
