# Generated by Django 3.1.6 on 2021-02-14 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0004_mod_downloads'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='downloads',
        ),
        migrations.CreateModel(
            name='ModsDownloadsCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddress', models.GenericIPAddressField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
            ],
        ),
    ]
