# Generated by Django 3.1.6 on 2021-04-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_auto_20210417_1242'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='comments',
            field=models.ManyToManyField(related_name='user_comments', to='mods.Mod'),
        ),
        migrations.AddField(
            model_name='user',
            name='mods',
            field=models.ManyToManyField(related_name='user_mods', to='mods.Mod'),
        ),
    ]
