# Generated by Django 3.1.6 on 2021-04-12 21:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project_box.apps.mods.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(help_text='Allowed format: PNG. Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg']), project_box.apps.mods.validators.validate_file_size_4mb])),
                ('header_image', models.ImageField(help_text='Allowed format: PNG. Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg']), project_box.apps.mods.validators.validate_file_size_4mb])),
                ('description', models.TextField(max_length=10000)),
                ('mod_file', models.FileField(help_text='Please upload a .zip file. Current max. size: 10Mb.', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip']), project_box.apps.mods.validators.validate_file_size_10mb])),
                ('mod_file_size', models.FloatField(blank=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('visible', models.BooleanField(default=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mod',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mods.modstype'),
        ),
        migrations.CreateModel(
            name='ModsDownloadsCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddress', models.GenericIPAddressField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
            ],
            options={
                'unique_together': {('mod_id', 'IPAddress')},
            },
        ),
    ]
