# Generated by Django 3.1.4 on 2021-01-25 15:08

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from project_box.apps.mods import validators
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(help_text='Allowed format: PNG. Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), validators.validate_file_size_4mb])),
                ('header_image', models.ImageField(help_text='Allowed format: PNG. Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png']), validators.validate_file_size_4mb])),
                ('description', tinymce.models.HTMLField(max_length=10000)),
                ('mod_file', models.FileField(help_text='Please upload a .zip file. Current max. size: 10Mb.', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['zip']), validators.validate_file_size_10mb])),
                ('mod_file_size', models.FloatField(blank=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('author', models.ForeignKey(default=django.contrib.auth.models.User, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ModsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulator', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModsListName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=50)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('list_owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('list_name', 'list_owner')},
            },
        ),
        migrations.CreateModel(
            name='ModsGallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=250, upload_to='')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('mod', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
            ],
        ),
        migrations.CreateModel(
            name='ModComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('visible', models.BooleanField(default=True)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_updated', models.DateTimeField(auto_now=True)),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mod',
            name='simulators',
            field=models.ManyToManyField(to='mods.Simulator'),
        ),
        migrations.AddField(
            model_name='mod',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mods.modstype'),
        ),
        migrations.CreateModel(
            name='ModsView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IPAddress', models.GenericIPAddressField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
            ],
            options={
                'unique_together': {('mod_id', 'IPAddress')},
            },
        ),
        migrations.CreateModel(
            name='ModsListConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('list_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.modslistname')),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('list_id', 'mod_id')},
            },
        ),
        migrations.CreateModel(
            name='ModsLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_liked', models.DateTimeField(auto_now_add=True)),
                ('mod_id', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to='mods.mod')),
                ('user_id', models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('mod_id', 'user_id')},
            },
        ),
    ]
