# Generated by Django 3.1.4 on 2021-01-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modsgallery',
            name='image_thumb',
            field=models.ImageField(blank=True, max_length=250, upload_to=''),
        ),
    ]
