# Generated by Django 3.1.6 on 2021-04-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2000)),
                ('visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='modsdownloadscounter',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modsdownloadscounter',
            name='mod_id',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='header_image',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='datetime_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='mod',
            old_name='datetime_updated',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='type',
        ),
        migrations.DeleteModel(
            name='ModComments',
        ),
        migrations.DeleteModel(
            name='ModsDownloadsCounter',
        ),
        migrations.DeleteModel(
            name='ModsType',
        ),
        migrations.AddField(
            model_name='type',
            name='mods',
            field=models.ManyToManyField(related_name='type_mods', to='mods.Mod'),
        ),
        migrations.AddField(
            model_name='mod',
            name='comments',
            field=models.ManyToManyField(related_name='user_comments', to='mods.Comment'),
        ),
        migrations.AddField(
            model_name='mod',
            name='downloads',
            field=models.ManyToManyField(related_name='mod_downloads', to='mods.Download'),
        ),
    ]
