# Generated by Django 3.1.6 on 2021-04-17 13:42

import django.core.validators
from django.db import migrations, models
import project_box.apps.mods.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0002_auto_20210417_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='comments',
            field=models.ManyToManyField(blank=True, related_name='user_comments', to='mods.Comment'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='cover_image',
            field=models.ImageField(help_text='Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg']), project_box.apps.mods.validators.validate_file_size_4mb]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='description',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='mod',
            name='downloads',
            field=models.ManyToManyField(blank=True, related_name='mod_downloads', to='mods.Download'),
        ),
        migrations.AlterField(
            model_name='mod',
            name='image',
            field=models.ImageField(help_text='Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg']), project_box.apps.mods.validators.validate_file_size_4mb]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='mod_file_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='visible',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
