# Generated by Django 3.1.6 on 2021-04-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0003_auto_20210417_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mod',
            name='mod_file_size',
        ),
        migrations.AddField(
            model_name='mod',
            name='uploading_to_cloud',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
