# Generated by Django 3.1.6 on 2021-04-17 20:21

import django.core.validators
from django.db import migrations, models
import project_box.apps.mods.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0004_auto_20210417_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='cover_image',
            field=models.FileField(help_text='Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg']), project_box.apps.mods.validators.validate_file_size_4mb]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='image',
            field=models.FileField(help_text='Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg']), project_box.apps.mods.validators.validate_file_size_4mb]),
        ),
    ]
