# Generated by Django 3.1.6 on 2021-02-14 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0005_auto_20210214_2353'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modsdownloadscounter',
            unique_together={('mod_id', 'IPAddress')},
        ),
    ]
