# Generated by Django 3.1.6 on 2021-04-18 07:05

import django.core.validators
from django.db import migrations, models
import project_box.apps.mods.validators


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0006_auto_20210417_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mod',
            name='cover_image',
            field=models.ImageField(help_text='Max. size: 4MB', upload_to='img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg']), project_box.apps.mods.validators.validate_file_size_4mb]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='image',
            field=models.ImageField(help_text='Max. size: 4MB', upload_to='img', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), project_box.apps.mods.validators.validate_file_size_4mb]),
        ),
    ]
