# Generated by Django 3.1.6 on 2021-04-12 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0006_auto_20210215_0020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modslike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modslike',
            name='mod_id',
        ),
        migrations.RemoveField(
            model_name='modslike',
            name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='modslistconnector',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modslistconnector',
            name='list_id',
        ),
        migrations.RemoveField(
            model_name='modslistconnector',
            name='mod_id',
        ),
        migrations.RemoveField(
            model_name='modslistconnector',
            name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='modslistname',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modslistname',
            name='list_owner',
        ),
        migrations.AlterUniqueTogether(
            name='modsview',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='modsview',
            name='mod_id',
        ),
        migrations.RenameField(
            model_name='modstype',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='mod',
            name='simulators',
        ),
        migrations.DeleteModel(
            name='ModsGallery',
        ),
        migrations.DeleteModel(
            name='ModsLike',
        ),
        migrations.DeleteModel(
            name='ModsListConnector',
        ),
        migrations.DeleteModel(
            name='ModsListName',
        ),
        migrations.DeleteModel(
            name='ModsView',
        ),
        migrations.DeleteModel(
            name='Simulator',
        ),
    ]
