# Generated by Django 3.1.6 on 2021-04-20 13:35

import django.core.validators
from django.db import migrations, models
import project_box.apps.mods.validators
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0007_auto_20210418_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='download',
            name='ip_address',
            field=models.GenericIPAddressField(default='', protocol='IPv4', unique=True),
        ),
        migrations.AlterField(
            model_name='mod',
            name='cover_image',
            field=models.ImageField(help_text='Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg']), project_box.apps.mods.validators.validate_file_size_4mb]),
        ),
        migrations.AlterField(
            model_name='mod',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='mod',
            name='image',
            field=models.ImageField(help_text='Max. size: 4MB', upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg']), project_box.apps.mods.validators.validate_file_size_4mb]),
        ),
    ]
