# Generated by Django 3.1.6 on 2021-04-25 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0009_auto_20210421_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='mods',
            field=models.ManyToManyField(null=True, related_name='type_mods', to='mods.Mod'),
        ),
    ]
