# Generated by Django 3.1.6 on 2021-04-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0010_auto_20210425_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='type',
            name='mods',
            field=models.ManyToManyField(blank=True, related_name='type_mods', to='mods.Mod'),
        ),
    ]
