# Generated by Django 3.1.6 on 2021-05-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mods', '0011_auto_20210425_0510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='mods',
        ),
        migrations.CreateModel(
            name='SubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mods', models.ManyToManyField(blank=True, related_name='sub_type_mods', to='mods.Mod')),
            ],
        ),
        migrations.AddField(
            model_name='type',
            name='subtypes',
            field=models.ManyToManyField(blank=True, related_name='type_sub_types', to='mods.SubType'),
        ),
    ]
